config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#show"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  delete '/logout', to: 'sessions#destroy'

  post '/users', to: 'users#create'
  resources :users, only: [:update]
  get '/dashboard', to: 'users#show'

  namespace :admin do
    get '/dashboard', to: 'users#show'
    delete '/user/:id', to: 'users#destroy'
    resources :users, only: [:update]
    get '/orders', to: 'orders#index'
  end

  get '/trip', to: 'trip_packages#show'
  post '/charges', to: 'charges#create'
  get '/charges/new', to: 'charges#new'
  get "/packages", to: "packages#index"
  post '/packages', to: 'packages#create'
  # get '/packages/:id', to: 'packages#show'
  resources :packages, only: [ :show]

  get '/logout', to: 'sessions#destroy'
  get '/orders', to: 'orders#index'

  # get '/trip_packages', to: 'trip_packages#show'
  post '/trip_packages', to: 'trip_packages#create'
  # patch '/trip_package/:id', to: 'trip_packages#update'
  # put '/trip_packages'
  delete '/trip_packages/:id', to: 'trip_packages#destroy'
  resources :trip_packages, only: [ :update]
  # get '/orders/:id', to: 'orders#show'
  get '/orders', to: 'orders#index'
  resources :orders, only: [:show]

  # get '/packages/:id', to: 'packages#show'
  # patch '/users/:id', to: 'users#update'
  # put '/users/:id', to: 'users#update'
  post '/orders', to: 'orders#create'

  get '/:planet', to: 'destinations#show', as: :destination
  get '/destinations', to: 'destinations#create'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_packages
  has_many :packages, through: :order_packages

  enum status: %w(Pending Paid Cancelled)

  def create_packages(trip)
    trip.itinerary.each_pair do |key, value|
      value.times do
        order_packages.create(user_id: user_id,
                              order_id: id,
                              package_id: key.to_i)
      end
    end
  end

  def package_total_price
    packages.sum(:price)
  end

  def package_quantity(package_id)
    order_packages.where(package_id: package_id).count
  end

  def total_quantity
    order_packages.count
  end

  def subtotal(package)
    package_quantity(package.id) * package.price
  end

  def format_time(time)
    time.strftime("%B %d, %Y @ %l:%M%p")
  end

  def package_names
    packages.pluck(:title).join(", ")
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = current_user.orders
  end

  def show
    if current_user.nil?
      render file: "/public/404"
    elsif current_user == Order.find(params[:id]).user || current_user.admin?
      @order = Order.find(params[:id])
    else
      render file: "/public/404"
    end
  end

  def create
    order = Order.create(user_id: current_user.id, total_cost: @trip.total_price, status: 1)
    order.create_packages(@trip)
    flash[:success] = "Order was Successfully Placed"
    session[:trip].clear
    redirect_to orders_path
  end

end

app/views/admin/orders/index.html.erb
<br>
<div class="row column">
  <% if @orders.nil? %>
    <h1>class="text-center">No Recent Orders</h1>
  <% else %>
  <h1 class="text-center">All Orders:</h1>
  <table>
    <thead>
      <tr>
        <th width "150">User</th>
        <th width "150">Order Id</th>
        <th width "200">Status
        <th width "150">Total Price</th>
        <th width "150">Passengers</th>
        <th width "300">Packages</th>
        <th width "200"></th>
      </tr>
    </thead>
    <tbody class= "orders">
      <tr>
        <% @orders.each do |order| %>
          <td><%= order.user.username %></td>
          <td><%= order.id %></td>
          <td> <%= order.status %>
          <td><%= order.total_cost%></td>
          <td><%= order.total_quantity%></td>
          <td><%= order.package_names %></td>
          <td><%= link_to "View", order_path(order), class: "button primary" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>