config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#show"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  delete '/logout', to: 'sessions#destroy'

  post '/users', to: 'users#create'
  resources :users, only: [:update]
  get '/dashboard', to: 'users#show'

  namespace :admin do
    get '/dashboard', to: 'users#show'
    delete '/user/:id', to: 'users#destroy'
    resources :users, only: [:update]
    get '/orders', to: 'orders#index'
  end

  get '/trip', to: 'trip_packages#show'
  post '/charges', to: 'charges#create'
  get '/charges/new', to: 'charges#new'
  get "/packages", to: "packages#index"
  post '/packages', to: 'packages#create'
  # get '/packages/:id', to: 'packages#show'
  resources :packages, only: [ :show]

  get '/logout', to: 'sessions#destroy'
  get '/orders', to: 'orders#index'

  # get '/trip_packages', to: 'trip_packages#show'
  post '/trip_packages', to: 'trip_packages#create'
  # patch '/trip_package/:id', to: 'trip_packages#update'
  # put '/trip_packages'
  delete '/trip_packages/:id', to: 'trip_packages#destroy'
  resources :trip_packages, only: [ :update]
  # get '/orders/:id', to: 'orders#show'
  get '/orders', to: 'orders#index'
  resources :orders, only: [:show]

  # get '/packages/:id', to: 'packages#show'
  # patch '/users/:id', to: 'users#update'
  # put '/users/:id', to: 'users#update'
  post '/orders', to: 'orders#create'

  get '/:planet', to: 'destinations#show', as: :destination
  get '/destinations', to: 'destinations#create'

end

app/views/shared/_dashboard.html.erb
<div class="row small-6 offset-3">
  <h4 class="centered-text">Welcome to Your Dashboard, <%= @user.username %></h4>
  <h4 class="centered-text"><%= @user.email %></h4>
</div>

<div class="row small-4 offset-4">
  <div class="accordian" data-accordian>
    <div class="accordian-item" data-accordian-item>
      <a href="#" class="accordian-title">Edit Account</a>
      <div class="accordian-content" data-tab-content>
        <%= form_for @user do |f| %>
        <%= f.text_field :username %>
        <%= f.text_field :email %>
        <%= f.password_field :password, placeholder: "New Password" %>
        <%= f.password_field :password_confirmation, placeholder: "Password confirmation" %>
        <%= f.submit "Update Account", class: "button expanded"%>
        <% end %>
      </div>
      <div class="accordian-item">
       <a href="#" class="accordian-title">Delete Account</a>
       <div class="accordian-content" data-tab-content>
         <h6 class="centered-text">Are You Sure? We'll Miss You So!</h6>
         <%= button_to "I\'m Sure- Delete my Account", user_path(@user), method: :delete, class: "button expanded" %>
       </div>
     </div>
    <% if current_user.admin? %>
      <div class="accordian-item" data-accordian-item>
        <a href="#" class="accordian-title">Create a New Destination</a>
        <div class="accordian-content" data-tab-content>
          <%= form_for @destination do |f| %>
          <%= f.text_field :planet, placeholder: "Enter a Planet, Nebula, or Region of Space" %>
          <%= f.submit class: "button expanded"%>
          <% end %>
        </div>
      </div>
      <div class="accordian-item" data-accordian-item>
        <a href="#" class="accordian-title">Create a New Package</a>
        <div class="accordian-content" data-tab-content>
          <%= form_for @package do |f| %>
          <%= f.text_field :title, placeholder: "Package Title" %>
          <%= f.text_area :description, placeholder: "Package Description" %>
          <%= f.label :price, "Choose a Price for the New Package" %>
          <%= f.number_field :price, in: 1000..10000, step: "any" %>
          <%= f.label :destination_id, "Choose a Destination for the New Package" %>
          <%= f.collection_select :destination_id, @destinations, :id, :planet, include_blank: true %>
          <%= f.label :image, "Choose an Image" %>
          <%= f.file_field :image %>
          <%= f.submit class: "button expanded"%>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_packages.html.erb
<div class="row small-up-1 medium-up-2 large-up-4 featured-packages">
  <% packages.each do |package| %>
  <div class="column">
    <h5 class="image-tag text-center"><%= link_to package.title, package_path(package), class: "package-tag" %></h5>
    <div class="image-wrapper overlay-fade-in">
      <%= image_tag package.image.url, class: "thumbnail" %>
      <div class="image-overlay-content">
        <h2><%= link_to "Explore", package_path(package) %></h2>
      </div>
    </div>
  </div>
  <% end %>
</div>