config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#show"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  delete '/logout', to: 'sessions#destroy'

  post '/users', to: 'users#create'
  resources :users, only: [:update]
  get '/dashboard', to: 'users#show'

  namespace :admin do
    get '/dashboard', to: 'users#show'
    delete '/user/:id', to: 'users#destroy'
    resources :users, only: [:update]
    get '/orders', to: 'orders#index'
  end

  get '/trip', to: 'trip_packages#show'
  post '/charges', to: 'charges#create'
  get '/charges/new', to: 'charges#new'
  get "/packages", to: "packages#index"
  post '/packages', to: 'packages#create'
  # get '/packages/:id', to: 'packages#show'
  resources :packages, only: [ :show]

  get '/logout', to: 'sessions#destroy'
  get '/orders', to: 'orders#index'

  # get '/trip_packages', to: 'trip_packages#show'
  post '/trip_packages', to: 'trip_packages#create'
  # patch '/trip_package/:id', to: 'trip_packages#update'
  # put '/trip_packages'
  delete '/trip_packages/:id', to: 'trip_packages#destroy'
  resources :trip_packages, only: [ :update]
  # get '/orders/:id', to: 'orders#show'
  get '/orders', to: 'orders#index'
  resources :orders, only: [:show]

  # get '/packages/:id', to: 'packages#show'
  # patch '/users/:id', to: 'users#update'
  # put '/users/:id', to: 'users#update'
  post '/orders', to: 'orders#create'

  get '/:planet', to: 'destinations#show', as: :destination
  get '/destinations', to: 'destinations#create'

end

app/controllers/trip_packages_controller.rb
class TripPackagesController < ApplicationController

  def create
    package = Package.find(params[:package_id])
    @trip.add_package(package.id)
    session[:trip] = @trip.itinerary
    flash[:success] = "You have added #{package.title} to your trip. Your current trip costs: #{@trip.total_price}."
    redirect_to package_path(package)
  end

   def show
    unless @trip.itinerary.nil?
      @packages = @trip.find_packages
    end
  end

  def update
    @trip.adjust_quantity(params[:operation], params[:id])
    redirect_to '/trip'
  end


  def destroy
    package = Package.find(params[:id])
    @trip.itinerary.delete(params[:id])
    flash[:warning] = "Successfully removed #{package.title} from your trip"

    redirect_to "/trip"
  end

end

app/views/trip_packages/_stripe.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @amount %>"
          data-locale="auto"></script>
<% end %>

app/views/trip_packages/show.html.erb
<br>
<div class="row column cart">
  <% if @trip.itinerary == {} %>
    <br>
    <h1 class= "text-center"> Your Cart is Empty </h1>
    <br>
  <% else %>
    <table>
      <thead>
        <tr>
          <th width "300"></th>
          <th width "200">Package Name</th>
          <th width "200" class="squish">Description</th>
          <th width "200">Price</th>
          <th width "100">Passengers</th>
          <th width "100">Sub Total</th>
          <th width "100"></th>

        </tr>
      </thead>
      <tbody class="package">
        <tr>
        <% @packages.each do |package| %>
            <td><%= image_tag package.image, class: "cart-image" %></td>
            <td><%= package.title %></td>
            <td><%= package.description %></td>
            <td><%= package.price %></td>
              <td><%= @trip.sub_quantity(package.id) %>
                <%= link_to "", trip_package_path(package, package.id, operation: "+"), method: 'patch', class: "fi-arrow-up" %>
                <% unless @trip.sub_quantity(package.id) == 1 %>
                  <%= link_to "", trip_package_path(package, package.id, operation: "-"), method: 'patch', class: "fi-arrow-down" %>
                <% end  %>
              </td>
            <td><%= @trip.subtotal(package) %></td>
            <td><%= link_to "", trip_package_path(package), method: :delete, class: "fi-x"  %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-right">Total Price: <%= @trip.total_price %></div>
    <div class="text-center">
      <% unless current_user %>
        <%= link_to "Login or Create Account to Purchase", login_path, class: "button primary" %>
      <% else %>
      <%= render partial: "stripe" %>
      <%= link_to "Checkout", orders_path, class: "hidden", method: :post %>
      <% end %>
    </div>
  <% end %>
  <br>
</div>