config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#show"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  delete '/logout', to: 'sessions#destroy'

  post '/users', to: 'users#create'
  resources :users, only: [:update]
  get '/dashboard', to: 'users#show'

  namespace :admin do
    get '/dashboard', to: 'users#show'
    delete '/user/:id', to: 'users#destroy'
    resources :users, only: [:update]
    get '/orders', to: 'orders#index'
  end

  get '/trip', to: 'trip_packages#show'
  post '/charges', to: 'charges#create'
  get '/charges/new', to: 'charges#new'
  get "/packages", to: "packages#index"
  post '/packages', to: 'packages#create'
  # get '/packages/:id', to: 'packages#show'
  resources :packages, only: [ :show]

  get '/logout', to: 'sessions#destroy'
  get '/orders', to: 'orders#index'

  # get '/trip_packages', to: 'trip_packages#show'
  post '/trip_packages', to: 'trip_packages#create'
  # patch '/trip_package/:id', to: 'trip_packages#update'
  # put '/trip_packages'
  delete '/trip_packages/:id', to: 'trip_packages#destroy'
  resources :trip_packages, only: [ :update]
  # get '/orders/:id', to: 'orders#show'
  get '/orders', to: 'orders#index'
  resources :orders, only: [:show]

  # get '/packages/:id', to: 'packages#show'
  # patch '/users/:id', to: 'users#update'
  # put '/users/:id', to: 'users#update'
  post '/orders', to: 'orders#create'

  get '/:planet', to: 'destinations#show', as: :destination
  get '/destinations', to: 'destinations#create'

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
<div class="small-6 columns small-centered">
  <div class="alert-box <%= type %> callout" data-alert data-closable >
    <i class="fi-info"></i>
    <%= message %>
    <button class"close-button" aria-label="Dismiss alert" type="button" data-close >
      <span class= "flash-close text-right", aria-hidden="true" >&times;</span>
    </button>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row">
    <div class="small-12 columns">
      <i class="fi-social-github"></i>
      <p class="links">
        <a href="https://github.com/Jbern16">Jon Bernesser</a>
        <a href="https://github.com/marinacor1">Marina Corona</a>
        <a href="https://github.com/jeneve">Jeneve Parish</a>
      </p>
    </div>
    <a href="https://www.turing.io/">Turing School</a>
  </div>
</footer>

app/views/layouts/_forms.html.erb
<br>
<div class="row small-4 offset-4">
  <ul class="accordion" data-accordion>
    <li class="accordion-item" data-accordion-item>
      <a href="#" class="accordian-title"><h3 class="text-center">Edit Your Username or Email</h3></a>
      <div class="accordion-content" data-tab-content>
        <%= form_for @user do |f| %>
        <%= f.text_field :username, placeholder: "Username" %>
        <%= f.text_field :email, placeholder: "Email" %>
        <%= f.password_field :password, placeholder: "Enter Password" %>
        <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
        <%= f.submit "Update Account", class: "button expanded"%>
        <% end %>
      </div>
    </li>
  </ul>
  </div>
  <br>
<div class="row small-4 offset-4 passwordchange">
  <ul class="accordion" data-accordion>
    <li class="accordion-item" data-accordion-item>
      <a href="#" class="accordian-title"><h3 class="text-center">Change Your Password</h3></a>
      <div class="accordion-content" data-tab-content>
        <%= form_for @user do |f| %>
        <%= f.password_field :password, placeholder: "New Password" %>
        <%= f.password_field :password_confirmation, placeholder: "Confirm New Password" %>
        <%= f.submit "Update Password", class: "button expanded"%>
        <% end %>
      </div>
    </li>
  </ul>
</div>

app/views/layouts/_nav.html.erb
<div data-sticky-container>
  <div class="title-bar nav" data-sticky data-options="marginTop: .065;" style="width:100%">
    <div class="title-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li>
        <a><i class="logo fi-torso"></i></a>
          <ul class="menu user-info">
            <% if current_user%>
              <li><%= link_to "#{current_user.username}'s Dashboard", dashboard_path if !current_user.admin? %></li>
              <li><%= link_to "#{current_user.username}'s Dashboard", admin_dashboard_path if current_user.admin? %></li>
              <li><%= link_to "Your Orders", orders_path  %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Login", login_path %></li>
            <% end  %>
         </ul>
       </li>
      </ul>
    </div>
    <div class="title-bar-right">
        <ul class="menu">
          <li><a href= "<%= trip_path %>" class="cart-icon">
            <i class="logo fi-shopping-bag"><span class="quantity"><%= @trip.quantity %></span></i>
            </a>
          </li>
        </ul>
    </div>
    <div class="menu-centered">
      <ul class = "menu">
        <a class="logo" href="/"><h3 class="logo">Eccentric<i class="fi-ticket"></i> Travel</h3></a>
        <hr size="1px">
        <% unless @destinations.nil? %>
          <% @destinations.each do |destination| %>
            <li><%= link_to destination.planet, destination_path(destination.planet), class: "button nav-button shadow" %></li>
          <% end %>
          <li><%= link_to "All Packages", packages_path, class: "button nav-button" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title><%= content_for?(:title) ? yield(:title) : "Eccentric" %></title>
  <link href='https://fonts.googleapis.com/css?family=Raleway:200|Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/nav' %>
  <%= render partial: 'layouts/flash' %>
  <%= yield %>
  <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>